openapi: 3.0.4
info:
  title: Kotlin wiz log models
  description: Log models for logging services of quiz
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: General log model
      description: Common log model for all microservices of the system
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        question:
          $ref: '#/components/schemas/QuizQuestionLogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    QuizQuestionLogModel:
      title: Log model for Quiz microservice
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - init
            - finish
        requestQuestion:
          $ref: '#/components/schemas/QuestionLog'
        requestFilter:
          $ref: '#/components/schemas/QuestionFilterLog'
        responseQuestion:
          $ref: '#/components/schemas/QuestionLog'
        responseQuestions:
          type: array
          items:
            $ref: '#/components/schemas/QuestionLog'

    ErrorLogModel:
      title: Error log model
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    QuestionLog:
      title: Log model for the question
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        answerOptions:
          type: array
          items:
            type: string
        answer:
          type: string
        explanation:
          type: string
        level:
          type: string
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    QuestionFilterLog:
      title: Filter log model
      properties:
        searchString:
          type: string
