name: 'ci-master'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'master'
      - 'release/*'

  workflow_dispatch:

jobs:
  build:
    env:
      USER: ${{ github.actor }}
      REPO: ${{ github.repository }}
      IMAGE_NAME: "kotlin-wiz"
    runs-on: ubuntu-latest
    steps:
      - name: Get files from repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: check -i

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: List contents of directories to check the location of JAR file
        run: |
          ls -la kotlin-wiz && \
          ls -la kotlin-wiz/wiz-service && \
          ls -la kotlin-wiz/wiz-service/build/libs

      - name: Build and push
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
